spring:
  datasource:
    url: jdbc:h2:mem:devdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jackson:
    serialization:
      write-dates-as-timestamps: false

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.example.app.domain

app:
  upload-dir: ${user.dir}/uploads
